2025-04-15 12:13:13 - INFO - logger - <module> - Приложение запущено
2025-04-15 12:13:13 - INFO - logger - <module> - Добавляем логирование в остальные файлы проекта...
2025-04-15 12:13:13 - INFO - logger - <module> - Логирование в database.py: все запросы к серверу регистрируются.
2025-04-15 12:13:13 - INFO - logger - <module> - Логирование в COM.py: события работы с COM-портами фиксируются.
2025-04-15 12:13:13 - INFO - logger - <module> - Логирование в detail_work.py: операции с деталями регистрируются.
2025-04-15 12:13:13 - INFO - logger - <module> - Логирование в Error.py и ErrorTest.py: ошибки записываются.
2025-04-15 12:13:13 - INFO - logger - <module> - Логирование в этапах Mark.py, Packing.py, Test.py, Work.py.
2025-04-15 12:13:15 - INFO - logger - log_event - Сервер доступен
2025-04-15 12:13:15 - INFO - logger - log_event - Сервер доступен
2025-04-15 12:13:15 - INFO - logger - log_event - Главное окно приложения создано
2025-04-15 12:13:15 - INFO - logger - log_event - SerialManager: Успешно открыт порт COM8
2025-04-15 12:13:16 - INFO - logger - log_event - Создан интерфейс админ-панели
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to mark
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Test
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Packing
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Login page AA
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to assembly
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to mark
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Test
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Packing
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Login page AA
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to assembly
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to mark
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Test
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Packing
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Login page AA
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to assembly
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to mark
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Test
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Packing
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Login page AA
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to assembly
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to mark
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Test
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Packing
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to Login page AA
2025-04-15 12:13:16 - INFO - logger - log_event - Enter to assembly
2025-04-15 12:13:16 - INFO - logger - log_event - Запущен мониторинг подключения к МЭТР
2025-04-15 12:13:17 - INFO - logger - log_event - Raw data (bytes): b'\xd0\x90\xd0\xb3\xd1\x83\xd0\xb0\xd0\xb3\xd1\x83\r\n'
2025-04-15 12:13:17 - INFO - logger - log_event - Decoded data (str): Агуагу
2025-04-15 12:13:17 - INFO - logger - log_event - Parsed Data: ['Агуагу']
2025-04-15 12:13:17 - INFO - logger - log_event - System МЭТР init
2025-04-15 12:13:24 - INFO - logger - log_event - Raw data (bytes): b'356949877_user..\r\n'
2025-04-15 12:13:24 - INFO - logger - log_event - Decoded data (str): 356949877_user..
2025-04-15 12:13:24 - INFO - logger - log_event - Parsed Data: ['356949877', 'user']
2025-04-15 12:13:24 - INFO - logger - log_event - Send data to handle_serial_data: ['356949877', 'user']
2025-04-15 12:13:24 - INFO - logger - log_event - Данные перед очисткой: ['356949877', 'user']
2025-04-15 12:13:24 - INFO - logger - log_event - Очищенные данные: ['356949877', 'user']
2025-04-15 12:13:24 - INFO - logger - log_event - Пользователь с UID: 356949877
2025-04-15 12:13:24 - INFO - logger - log_event - Попытка аутентификации пользователя с UID: 356949877
2025-04-15 12:13:24 - INFO - logger - log_event - Запрос: {'type': 'user', 'uid': '356949877', 'id': None}
2025-04-15 12:13:24 - INFO - logger - log_event - Ответ: {'status': 'ok', 'name': 'Дмитрий', 'surname': 'Волков', 'id': 2}
2025-04-15 12:13:24 - INFO - logger - log_event - Ответ сервера: {'status': 'ok', 'name': 'Дмитрий', 'surname': 'Волков', 'id': 2}
2025-04-15 12:13:24 - INFO - logger - log_event - Данные пользователя в корне ответа: {'status': 'ok', 'name': 'Дмитрий', 'surname': 'Волков', 'id': 2}
2025-04-15 12:13:24 - INFO - logger - log_event - Raw data (bytes): b'\r\n'
2025-04-15 12:13:24 - INFO - logger - log_event - Decoded data (str): 
2025-04-15 12:13:24 - INFO - logger - log_event - Get NULL
2025-04-15 12:13:25 - INFO - logger - log_event - Запрос на создание сессии: {'type': 'startSession', 'name': 'Дмитрий', 'surname': 'Волков', 'work_description': 'Без детали'}
2025-04-15 12:13:25 - INFO - logger - log_event - Запрос: {'type': 'startSession', 'name': 'Дмитрий', 'surname': 'Волков', 'work_description': 'Без детали', 'id': None}
2025-04-15 12:13:27 - INFO - logger - log_event - Ответ: {'status': 'ok'}
2025-04-15 12:13:27 - INFO - logger - log_event - Ответ на создание сессии: {'status': 'ok'}
2025-04-15 12:13:27 - INFO - logger - log_event - Сессия успешно начата: Волков Дмитрий
2025-04-15 12:13:27 - INFO - logger - log_event - Устанавливаем переменную config.user: Волков Дмитрий
2025-04-15 12:13:27 - INFO - logger - log_event - Устанавливаем переменную config.Name: Волков Дмитрий
2025-04-15 12:13:27 - INFO - logger - log_event - Установлено значение config.Name: Волков Дмитрий
2025-04-15 12:13:27 - INFO - logger - log_event - Успешная аутентификация пользователя: Волков Дмитрий
2025-04-15 12:13:29 - ERROR - logger - log_error - Ошибка: SerialListener: Ошибка COM-порта: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\COM.py", line 89, in run
    if self.ser.in_waiting > 0:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
2025-04-15 12:13:31 - ERROR - logger - log_error - Ошибка: SerialListener: Ошибка COM-порта: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\COM.py", line 89, in run
    if self.ser.in_waiting > 0:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
2025-04-15 12:13:33 - ERROR - logger - log_error - Ошибка: SerialListener: Ошибка COM-порта: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\COM.py", line 89, in run
    if self.ser.in_waiting > 0:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
2025-04-15 12:13:35 - ERROR - logger - log_error - Ошибка: SerialListener: Ошибка COM-порта: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\COM.py", line 89, in run
    if self.ser.in_waiting > 0:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
2025-04-15 12:13:37 - ERROR - logger - log_error - Ошибка: SerialListener: Ошибка COM-порта: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\COM.py", line 89, in run
    if self.ser.in_waiting > 0:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
2025-04-15 12:13:37 - ERROR - logger - log_error - Ошибка: SerialListener: Превышено максимальное количество попыток переподключения
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RFID-marks\GUI\COM.py", line 89, in run
    if self.ser.in_waiting > 0:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Отказано в доступе.', None, 5))
2025-04-15 12:13:37 - ERROR - logger - log_error - Ошибка: Получен сигнал о потере соединения с МЭТР
NoneType: None
2025-04-15 12:13:39 - INFO - logger - log_event - Остановлен текущий слушатель COM-порта
2025-04-15 12:13:39 - INFO - logger - log_event - SerialManager: Порт COM8 закрыт
2025-04-15 12:13:39 - INFO - logger - log_event - Закрыто текущее соединение с COM-портом
2025-04-15 12:13:39 - INFO - logger - log_event - SerialManager: Успешно открыт порт COM8
2025-04-15 12:13:39 - INFO - logger - log_event - Создан новый SerialManager с портом COM8
2025-04-15 12:13:39 - INFO - logger - log_event - Запущен новый слушатель COM-порта
2025-04-15 12:13:39 - INFO - logger - log_event - Обновлена ссылка на SerialManager в Ui_MainWindow
2025-04-15 12:13:39 - INFO - logger - log_event - Обновлена ссылка на SerialManager в Ui_MainWindow
2025-04-15 12:13:39 - INFO - logger - log_event - Глобальное переподключение к МЭТР выполнено успешно
2025-04-15 12:13:40 - INFO - logger - log_event - Raw data (bytes): b'W'
2025-04-15 12:13:40 - INFO - logger - log_event - Decoded data (str): W
2025-04-15 12:13:40 - INFO - logger - log_event - Parsed Data: ['W']
2025-04-15 12:13:40 - ERROR - logger - log_error - Ошибка: Error, Incorrect data to send: ['W']
NoneType: None
2025-04-15 12:13:41 - INFO - logger - log_event - Raw data (bytes): b'\xd0\x90\xd0\xb3\xd1\x83\xd0\xb0\xd0\xb3\xd1\x83\r\n'
2025-04-15 12:13:41 - INFO - logger - log_event - Decoded data (str): Агуагу
2025-04-15 12:13:41 - INFO - logger - log_event - Parsed Data: ['Агуагу']
2025-04-15 12:13:41 - INFO - logger - log_event - System МЭТР init
2025-04-15 12:13:45 - INFO - logger - log_event - Raw data (bytes): b'356949877_user..\r\n'
2025-04-15 12:13:45 - INFO - logger - log_event - Decoded data (str): 356949877_user..
2025-04-15 12:13:45 - INFO - logger - log_event - Parsed Data: ['356949877', 'user']
2025-04-15 12:13:45 - INFO - logger - log_event - Send data to handle_serial_data: ['356949877', 'user']
2025-04-15 12:13:45 - INFO - logger - log_event - Данные перед очисткой: ['356949877', 'user']
2025-04-15 12:13:45 - INFO - logger - log_event - Очищенные данные: ['356949877', 'user']
2025-04-15 12:13:45 - INFO - logger - log_event - Пользователь с UID: 356949877
2025-04-15 12:13:45 - INFO - logger - log_event - Raw data (bytes): b'\r\n'
2025-04-15 12:13:45 - INFO - logger - log_event - Decoded data (str): 
2025-04-15 12:13:45 - INFO - logger - log_event - Get NULL
